#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import requests
import re
import sys
from urllib.parse import urlparse
from datetime import datetime

# ================== 配置区（这是你需要关注的地方） ==================
# 🔴 在这里填写你的直播源地址，可以填多个，一行一个
SOURCE_URLS = [
    # 以下地址仅为示例，你需要替换为自己确认可用的地址
    "https://0701.tv1288.xyz",
]

# 可选：如果你想过滤频道，可以在这里写关键词，比如 ["CCTV", "卫视"]，留空则不过滤
FILTER_KEYWORDS = []  

# 输出文件名
OUTPUT_FILE = "iptv_playlist.m3u"
# ================================================================

def fetch_playlist(url):
    """获取并返回直播源文本"""
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        }
        resp = requests.get(url, headers=headers, timeout=15)
        resp.raise_for_status()
        return resp.text
    except Exception as e:
        print(f"❌ 获取 {url} 失败: {e}")
        return None

def parse_and_filter(content):
    """简单解析并可选过滤"""
    lines = content.splitlines()
    result = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        
        # 如果有过滤关键词，只保留包含关键词的行
        if FILTER_KEYWORDS:
            if any(kw.lower() in line.lower() for kw in FILTER_KEYWORDS):
                result.append(line)
        else:
            result.append(line)
    return result

def main():
    print(f"[{datetime.now()}] 🚀 开始更新直播源...")
    
    all_lines = ["#EXTM3U", f"# Generated by process.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"]
    
    success_count = 0
    for url in SOURCE_URLS:
        print(f"📡 正在抓取: {url}")
        content = fetch_playlist(url)
        if content:
            parsed = parse_and_filter(content)
            all_lines.extend(parsed)
            success_count += 1
            print(f"   ✅ 成功获取 {len(parsed)} 行内容")
        else:
            print(f"   ❌ 抓取失败")
    
    # 写入文件
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(all_lines))
    
    print(f"[{datetime.now()}] ✅ 完成！共从 {success_count} 个源获取数据，播放列表已保存到: {OUTPUT_FILE}")
    print(f"   文件行数: {len(all_lines)}")

if __name__ == "__main__":
    main()
